export const delegaciones = [
    "Delegacion Deparamental La Plata",
    "Delegacion Deparamental Azul",
    "Delegacion Deparamental Bahia Blanca",
    "Delegacion Deparamental Dolores",
    "Delegacion Deparamental Exaltacion de la Cruz",
    "Delegacion Deparamental Junin",
    "Delegacion Deparamental La Matanza",
    "Delegacion Deparamental Lomas de Zamora",
    "Delegacion Deparamental Mar del Plata",
    "Delegacion Deparamental Mercedes",
    "Delegacion Deparamental Moron",
    "Delegacion Deparamental Necochea",
    "Delegacion Deparamental Pergamino",
    "Delegacion Deparamental Pilar",
    "Delegacion Deparamental Pinamar",
    "Delegacion Deparamental Quilmes",
    "Delegacion Deparamental San Isidro",
    "Delegacion Deparamental San Martin",
    "Delegacion Deparamental San Nicolas",
    "Delegacion Deparamental Trenque Lauquen",
    "Delegacion Deparamental Zarate",
    "Subdelegacion Departamental Tandil",
    "Subdelegacion Departamental Olavarria",
    "Subdelegacion Departamental Tres Arroyos",
    "Subdelegacion Departamental Cañuelas",
    "Subdelegacion Departamental San Vicente",
    "Subdelegacion Departamental Tres de Febrero",
    "Direccion Reunion de Informacion"
]