export const localidades = [
    "Adolfo Gonzalez Chavez",
    "Adrogé",
    "Alberti",
    "Aldo Bonzi",
    "Alejandro Korn",
    "America",
    "Arrecifes",
    "Avellaneda",
    "Ayacucho",
    "Azul",
    "Bahia Blanca",
    "Bajo Hondo",
    "Balcarce",
    "Banfield",
    "Baradero",
    "Batan",
    "Beccar",
    "Bella Vista",
    "Benavidez",
    "Benito Juarez",
    "Berazategui",
    "Beriso",
    "Bernal",
    "Bolivar",
    "Bosques",
    "Boulogne Sur Mer",
    "Bragado",
    "Brandsen",
    "Burzaco",
    "Campana",
    "Cañuelas",
    "Capitán del Señor",
    "Capitán Sarmiento",
    "Carhué",
    "Carlos Casares",
    "Carlos Spegazzini",
    "Carlos Tejedor",
    "Carmen de Areco",
    "Carmen de Patagones",
    "Casbas",
    "Caseros",
    "Castelar",
    "Castelli",
    "Chacabuco",
    "Chascomús",
    "Chivilcoy",
    "Ciudad Evita",
    "Claypole",
    "Colon",
    "Comandante Nicanor Otamendi",
    "Coronel Dorrego",
    "Coronel Pringles",
    "Coronel Rosales",
    "Coronel Suárez",
    "Coronel Vidal",
    "Cuartel V",
    "Daireaux",
    "Dock Sud",
    "Dolores",
    "Don Torcuato",
    "Eduardo O'Briend",
    "El Jagüel",
    "El Palomar",
    "El Talar",
    "Ensenada",
    "Escobar",
    "Esteban Echeverria",
    "Ezeiza",
    "Ezpeleta",
    "Florencio Varela",
    "Florentino Ameghino",
    "Francisco Álvarez",
    "Garin",
    "General Alvear",
    "General Arenales",
    "General Belgrano",
    "General Conesa",
    "General Daniel Cerri",
    "General Guido",
    "General Juan Madariaga",
    "General Las Heras",
    "General Lavalle",
    "General Lamadrid",
    "General pacheco",
    "General Pinto", 
    "General Rodriguez",
    "General Villegas",
    "Gerli",
    "Glew",
    "Gonzalez Catan",
    "Gregorio Laferrere",
    "Guaminí",
    "Guernica",
    "Haedo",
    "Henderson",
    "Hudson",
    "Hurlingham",
    "Ingeniero Budge",
    "Ingeniero Maschwitz",
    "Ingeniero White",
    "Isidro Casanova",
    "Ituzaingó",
    "Jeppener",
    "José C Paz",
    "Junin",
    "La Emilia",
    "La Plata",
    "La Reja",
    "La Tablada",
    "La Union",
    "Lanus",
    "Laprida",
    "Las Flores",
    "Lezama",
    "Lincoln",
    "Lavallol",
    "Lobería",
    "Lobos",
    "Loma Hermosa",
    "Lomas de Zamora",
    "Lomas del Mirador",
    "Longchamps",
    "Los Cardales",
    "Los Polvorines",
    "Los Toldos",
    "Luis Guillon",
    "Lujan",
    "Magdalena",
    "Maipú",
    "Maquinista Savio",
    "Mar Azul",
    "Mar de Ajó",
    "Mar del Plata",
    "Mar del Tuyú",
    "Marcos Paz",
    "Mariano Acosta",
    "Martin Coronado",
    "Martinez",
    "Medanos",
    "Mercedes",
    "Merlo",
    "Miramar",
    "Mones Cazón",
    "Monte",
    "Monte Chingolo",
    "Monte Grande",
    "Monte Hermoso",
    "Moreno",
    "Morón",
    "Navarro",
    "Necochea",
    "Nueve de Julio",
    "Olavarria",
    "Olivos",
    "Paso del Rey",
    "Pehuajó",
    "Pellegrini",
    "Pergamino",
    "Pigüe",
    "Pila",
    "Pilar",
    "Pinamar",
    "Pontavedra",
    "Presidente Derqui",
    "Puan",
    "Punta Alta",
    "Punta Indio",
    "Quequén",
    "Quilmes",
    "Rafael Calzada",
    "Rafael Castillo",
    "Ramallo",
    "Rauch",
    "Rawson",
    "Remedios de Escalada",
    "Rojas",
    "Roque Perez",
    "Saavedra",
    "Saladillo",
    "Salto",
    "San Andrés de Giles",
    "San Antonio de Areco",
    "San Antonio de Padua",
    "San Cayetano",
    "San Clemente del Tuyú",
    "San Fernando",
    "San Francisco Solano",
    "San Isidro",
    "San Justo",
    "San Martin",
    "San Nicolás de los Arroyos",
    "San Pedro",
    "San Vicente",
    "Santa Maria",
    "Sarandí",
    "Suipacha",
    "Tandil",
    "Tapalqué",
    "Tapiales",
    "Temperley",
    "Tigre",
    "Torquist",
    "Tortuguitas",
    "Treinta de Agosto",
    "Trenque Lauquen",
    "Tres Arroyos",
    "Tres Lomas",
    "Tristán Suárez",
    "Turdera",
    "Valentín Alsina",
    "Vedia",
    "Veinticinco de Mayo",
    "Vicente López",
    "Villa Ballester",
    "Villa Celina",
    "Villa Dorrego",
    "Villa Elisa",
    "Villa Fiorito",
    "Villa Gesel",
    "Villa Luzuriaga",
    "Villa Madero",
    "Villa Ramallo",
    "Villa Tesei",
    "Villarino",
    "Virrey del Pino",
    "Virreyes",
    "Wilde",
    "Zárate"
]