export const partidos = [
    "Adolfo Alsina",
    "Adolfo Gonzalez Chavez",
    "Alberti",
    "Almirante Brown",
    "Arrecifes",
    "Avellaneda",
    "Ayacucho",
    "Azul",
    "Bahia Blanca",
    "Balcarce",
    "Baradero",
    "Benito Juarez",
    "Berazategui",
    "Beriso",
    "Bolivar",
    "Bragado",
    "Brandsen",
    "CABA",
    "Campana",
    "Cañuelas",
    "Capitán Sarmiento",
    "Carlos Casares",
    "Carlos Tejedor",
    "Carmen de Areco",
    "Castelli",
    "Chacabuco",
    "Chascomús",
    "Chivilcoy",
    "Colon",
    "Coronel Dorrego",
    "Coronel Pringles",
    "Coronel Suárez",
    "Daireaux",
    "Dolores",
    "Ensenada",
    "Escobar",
    "Esteban Echeverria",
    "Exaltacion de la Cruz",
    "Ezeiza",
    "Florencio Varela",
    "Florentino Ameguhino",
    "General Alvarado",
    "General Alvear",
    "General Arenales",
    "General Belgrano",
    "General Conesa",
    "General Guido",
    "General Juan Madariaga",
    "General Lamadrid",
    "General Las Heras",
    "General Lavalle",
    "General Paz",
    "General Pinto",
    "General Pueyrredón",
    "General Rodriguez",
    "General San Martin",
    "General Viamonte",
    "General Villegas",
    "Guaminí",
    "Hipólito Yrigoyen",
    "Hurlingham",
    "Ituzaingó",
    "José C Paz",
    "Junin",
    "La Costa",
    "La Matanza",
    "La Plata",
    "Lanus",
    "Laprida",
    "Las Flores",
    "Leandro N. Alem",
    "Lezama",
    "Lincoln",
    "Lobería",
    "Lobos",
    "Lomas de Zamora",
    "Lujan",
    "Magdalena",
    "Maipú",
    "Malvinas Argentinas",
    "Mar Chiquita",
    "Mar del Plata",
    "Marcos Paz",
    "Mercedes",
    "Merlo",
    "Monte",
    "Monte Hermoso",
    "Moreno",
    "Morón",
    "Navarro",
    "Necochea",
    "Nueve de Julio",
    "Olavarria",
    "Patagones",
    "Pehuajó",
    "Pellegrini",
    "Pergamino",
    "Pila",
    "Pilar",
    "Pinamar",
    "Presidente Perón",
    "Puan",
    "Punta Indio",
    "Quilmes",
    "Ramallo",
    "Rauch",
    "Rivadavia",
    "Rojas",
    "Roque Perez",
    "Saavedra",
    "Saladillo",
    "Salto",
    "San Andrés de Giles",
    "San Antonio de Areco",
    "San Cayetano",
    "San Fernando",
    "San Isidro",
    "San Miguel",
    "San Nicolás",
    "San Pedro",
    "San Vicente",
    "Suipacha",
    "Tandil",
    "Tapalqué",
    "Tapiales",
    "Temperley",
    "Tigre",
    "Tordillo",
    "Torquist",
    "Trenque Lauquen",
    "Tres Arroyos",
    "Veinticinco de Mayo",
    "Vicente López",
    "Villa Gesel",
    "Villarino",
    "Zárate"
]